# Generated by Django 5.2.8 on 2025-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_codigoconvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Confirmada'), ('R', 'Rejeitada'), ('X', 'Cancelada'), ('M', 'Em Manutenção')], default='P', max_length=1),
        ),
    ]
