# Generated by Django 6.0 on 2025-12-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='recursos/'),
        ),
    ]
